spring:
  jpa:
    database: POSTGRESQL
    properties.hibernate.temp.use_jdbc_metadata_defaults: false
    hibernate:
      ddl-auto: none
    properties:
  datasource:
    platform: postgres
    url: jdbc:postgresql://localhost:5432/dsposit_db
    username: root
    password: root
    driver-class-name: org.postgresql.Driver

  rabbitmq:
    port: 5672
    host: rabbitmq
    username: guest
    password: guest
    listener:
      direct:
        default-requeue-rejected: true
